version: '3'

services:
  apache:
    image: httpd:2.4
    volumes:
      - ./www:/var/www/html
      - ./etc/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - apache

  php:
    build:
      ./etc/php
    volumes:
      - ./www:/var/www/html
      - ./etc/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.3
    volumes:
      - ./etc/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:db
    ports:
      - 8765:80
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
    depends_on:
      - mariadb